--- # creating directory
- name: creating a directory
  hosts: all
  user: ansible
  become: yes
  connection: ssh
  tasks:
    - name: creating a directory
      file: 
        path: /home/ansible/awsdirectory
        state: directory
           
